[package]
name = "spaceapi"
version = "0.1.0"
edition = "2021"
authors = ["Raphael Nestler <raphael.nestler@renuo.ch>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
