[package]
name = "spaceapi"
version = "0.1.0"
edition = "2021"
authors = ["Raphael Nestler <raphael.nestler@renuo.ch>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
serde_magnus = "0.8.1"
spaceapi = "0.9.0"
serde_json = "1.0.132"
